spring:
  datasource:
    url: jdbc:mysql://mysql:3306/gradletest?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none  # Flywayがスキーマ管理するため、Hibernateの自動DDLを無効化
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false
  application:
    name: gradle-test
  jackson:
    time-zone: Asia/Tokyo

server:
  port: 8080

logging:
  level:
    com.example.gradletest: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
